# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=3.16.1+multiloader
maven_group=fr.estecka.variantscit
archives_base_name=variants-cit
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4
yarn_mappings = 1.21.4+build.1

# Dependencies
architectury_api_version = 15.0.3
fabric_loader_version = 0.18.4
fabric_api_version = 0.119.4+1.21.4
neoforge_version = 21.4.155
yarn_mappings_patch_neoforge_version = 1.21+build.6
