modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Estecka/mc-Variants-CIT/issues"
license = "EUPL-1.2"

[[mods]]
modId = "variantscit"
version = "3.99+1.21.4"
displayName = "Variants CIT"
authors = "Estecka"
description = '''
Alternative CIT format for large collections of variants.
'''
logoFile = "assets/variants-cit/icon.png"

[[dependencies.variants-cit]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.variants-cit]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.21.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.variants-cit]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "variants-cit.mixins.json"
